### ISSUE TITLE
Can't install package: ModuleNotFoundError

### ISSUE THREAD

**Issue by Podbrushkin** [yaph/wikidata-dl#3]
* wikidata-dl version: wikidata_dl-2022.11.4-py3-none-any.whl
* Python version: 3.11.0
* Operating System: Windows 10

### Description

I was trying to launch your utility by executing  `pip install wikidata-dl`, but this command failed. I have tried both 3.8 and 3.11 Python.
I have no expirience with Python. Is this a problem with a pycurl package? How can I use your command-line program?

### What I Did
`pip install wikidata-dl`
..or..
`pip install https://github.com/yaph/wikidata-dl/archive/refs/tags/2022.11.04.zip`
both result in

```

Collecting pycurl
  Using cached pycurl-7.45.1.tar.gz (233 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\User\AppData\Local\Temp\pip-install-vm_6kuce\pycurl_abb48455cef74a459f73277eb7e3e2df\setup.py", line 954, in <module>
          setup_args['cmdclass'] = {'bdist_msi': get_bdist_msi_version_hack()}
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-install-vm_6kuce\pycurl_abb48455cef74a459f73277eb7e3e2df\setup.py", line 594, in get_bdist_msi_version_hack
          from distutils.command.bdist_msi import bdist_msi
      ModuleNotFoundError: No module named 'distutils.command.bdist_msi'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by yaph** [comment]
Python 3.8 isn't supported by `wikidata-dl` and I haven't tried Python 3.11 yet. Can you install `pycurl` by itself with `pip install pycurl`?

**Comment by Podbrushkin** [comment]
`pip install pycurl` was failing with the same error. But finally I was able to launch your application, what I did is:

- Installed Python 3.10
- Following [this SO](https://stackoverflow.com/a/47134766/), downloaded officially unavailable pycurl win64 binaries from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pycurl)
- `pip install pycurl-7.45.1-cp310-cp310-win_amd64.whl`
- `pip install wikidata-dl`
- `wikidata-dl --help`

Maybe there was no need in installing Python 3.10, since there are 3.8 and 3.11 packages available as well, I don't know.

**Comment by yaph** [comment]
Glad you found a way to install it!
